# service
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: LoadBalancer
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-image
        image: container28562yk.azurecr.io/sample-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7860
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "400Mi"
            cpu: "1000m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"